---
#- hosts: all
#- import_playbook: ../static-assignments/common.yml
# - import_playbook: ../static-assignments/common dev.yml

- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yml